@startuml
    class InventoryManager {
        /' class attributes '/
        - tools: List<Tool>
        - suppliers: List<Supplier>
        - orders" List<Order>

        /' create|add tools '/
        - addTools(tool: Tool): void

        /' delete tools '/
        - deleteTool(toolId: int): void

        /' read tools '/
        - searchByName(name: String): list
        - searchById(toolId: int): Tool
        - checkStock(): void

        /' update tools '/
        - makeOrder(): void

        /' file handler '/
        - loadToolsFromFile(): void
        - loadSuppliersFromFile(): void
        - exportOrder(orderData: HashMap): void
    }

    class Tool {
        /' class attributes '/
        - toolId: int
        - name: String
        - stock: int
        - price: double
        - supplierId: int

        /' get data '/
        + getToolById(): Tool
        + getToolByName(): Tool
        + checkStock(): boolean

        /' update data '/
        + decreaseQuantity()
        + increaseQuantity()
    }

    class Supplier {
        /' class attributes '/
        - supplierId: int
        - company: String
        - address: String
        - contact: String

        /' read data '/
        getSupplierById(): Supplier
    }

    class Order {
        /' class attributes '/
        - tool: Tool
        - supplier: Supplier
        - allOrders: List<OrderLine>

        /' creates one order '/
        + addOrderLine(orderLine: OrderLine)
    }

    class OrderLine {
        /' class attributes '/
        - orderId: Tool
        - quantity: int

        /' check stock '/
        + checkStock()
    }

    class FileHandler {
        /' read files '/
        + {static} readToolsFromFile(): List<Tool>
        + {static} readSuppliersFromFile(): List<Supplier>
        + {static} writeOrderToFile(order: Order): void
    }

    /' relationships for InventoryManager '/
    InventoryManager --> FileHandler
    InventoryManager o-- Tool
    InventoryManager o-- Supplier
    InventoryManager o-- Order

    /' relationships for Tool and Supplier '/
    Tool -->  Supplier

    /' relationships for Order '/
    Order *-- OrderLine

    /' relationships for OrderLine '/
    OrderLine --> Tool
@enduml